include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT "dmitriysd9202@gmail.com")
set(CPACK_PACKAGE_NAME "solverapp")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quadratic equation solver")
set(CPACK_PACKAGE_VERSION "${SOLVER_VERSION}")
set(CPACK_PACKAGE_VENDOR "${GITHUB_USERNAME}")

set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

 # set(CPACK_GENERATOR "DEB;RPM;WIX;DragNDrop")

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")

set(CPACK_SOURCE_INSTALLED_DIRECTORIES
    "${CMAKE_SOURCE_DIR}/solver_application; solver_application"
    "${CMAKE_SOURCE_DIR}/solver_lib; solver_lib"
    "${CMAKE_SOURCE_DIR}/formatter_ex_lib; formatter_ex_lib"
    "${CMAKE_SOURCE_DIR}/formatter_lib; formatter_lib"
)

# DEB
set(CPACK_DEBIAN_PACKAGE_NAME "solverapp")
set(CPACK_DEBIAN_PACKAGE_VERSION "${SOLVER_VERSION}")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Solves quadratic equations")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")

# RPM
set(CPACK_RPM_PACKAGE_NAME "solverapp")
set(CPACK_RPM_PACKAGE_VERSION "${SOLVER_VERSION}")
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_SUMMARY "Quadratic equation solver")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md")

# MSI (Windows)
set(CPACK_WIX_UPGRADE_GUID "51646d65-a4f9-497f-a814-8d5d7083977c")   
# DMG (macOS)
set(CPACK_DMG_VOLUME_NAME "solver-${SOLVER_VERSION}")
set(CPACK_DMG_FORMAT "UDBZ")

set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.rtf")

include(CPack)
